# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-msk
  description: This component is responsible for provisioning [Amazon Managed Streaming](https://aws
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
